import AppKit

/// A `termy://` deeplink. Registering the URL scheme requires `CFBundleURLTypes`
/// in the app's Info.plist (generated by `crates/xtask/src/macos.rs`); the
/// app-side parsing and routing below are independent of that registration.
enum TermyDeeplink: Equatable {
    case newTab
    case openSettings
    case openConfig
    case installTheme(slug: String)

    init?(url: URL) {
        guard url.scheme == "termy" else {
            return nil
        }
        let host = url.host?.lowercased() ?? ""
        let path = url.pathComponents.filter { $0 != "/" }
        switch host {
        case "new":
            self = .newTab
        case "settings":
            self = .openSettings
        case "config":
            self = .openConfig
        case "open" where path.first == "config":
            self = .openConfig
        case "store" where path.first == "theme-install":
            guard let slug = URLComponents(url: url, resolvingAgainstBaseURL: false)?
                .queryItems?.first(where: { $0.name == "slug" })?.value,
                !slug.isEmpty
            else {
                return nil
            }
            self = .installTheme(slug: slug)
        default:
            return nil
        }
    }
}

@MainActor
enum TermyDeeplinkRouter {
    /// Parses and dispatches a `termy://` URL. Unrecognized URLs are ignored —
    /// the input is external and untrusted, so rejecting it is correct.
    static func handle(_ url: URL) {
        guard let deeplink = TermyDeeplink(url: url) else {
            return
        }
        switch deeplink {
        case .newTab:
            NativeTabWindowManager.shared.openNativeTab()
        case .openSettings:
            NotificationCenter.default.post(name: .termyOpenSettingsRequested, object: nil)
        case .openConfig:
            _ = TermyNativeAppActions.openConfigFileInEditor()
        case .installTheme(let slug):
            guard confirmThemeInstall(slug: slug) else {
                return
            }
            do {
                try SettingsBridge.installTheme(slug: slug)
                TermyConfigurationStore.shared.reload()
                NotificationCenter.default.post(name: .termySettingsChanged, object: nil)
                TermyToastCenter.shared.show("Installed theme \(slug)", kind: .success)
            } catch {
                TermyErrorPresenter.present("Couldn't install theme", error: error)
            }
        }
    }

    private static func confirmThemeInstall(slug: String) -> Bool {
        let alert = NSAlert()
        alert.alertStyle = .informational
        alert.messageText = "Install theme?"
        alert.informativeText = "Termy will download and switch to \"\(slug)\"."
        alert.addButton(withTitle: "Install")
        alert.addButton(withTitle: "Cancel")
        return alert.runModal() == .alertFirstButtonReturn
    }
}
