[package]
name = "termy_api"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "termy-api"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
axum = "0.8"
better-auth = { version = "0.8", features = ["sqlx-postgres", "axum"] }
neon-serverless-sqlx = { git = "https://github.com/lassejlv/neon-serverless-sqlx", rev = "8d58d048e3ff39c155419301f5c9c511cd05f1f5" }
serde_json = { workspace = true }
sqlx = { version = "0.8", default-features = false, features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
  "migrate",
] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
